CREATE DATABASE QL_PHONGHOP;
GO
USE QL_PHONGHOP;
GO
CREATE TABLE TOA_NHA (
    MaToaNha CHAR(10) PRIMARY KEY,
    TenToaNha NVARCHAR(100),
    DiaChi NVARCHAR(200)
);

CREATE TABLE LOAI_PHONG (
    MaLoai CHAR(10) PRIMARY KEY,
    TenLoai NVARCHAR(50),
    MoTa NVARCHAR(200)
);
CREATE TABLE TRANGTHAI_PHONG (
    MaTrangThai CHAR(10) PRIMARY KEY,
    TenTrangThai NVARCHAR(50)
);
CREATE TABLE PHONG (
    MaPhong CHAR(10) PRIMARY KEY,
    TenPhong NVARCHAR(100),
    MaToaNha CHAR(10),
    MaLoai CHAR(10),
    SucChua INT,
    MaTrangThai CHAR(10),
    GhiChu NVARCHAR(200),
    FOREIGN KEY (MaToaNha) REFERENCES TOA_NHA(MaToaNha),
    FOREIGN KEY (MaLoai) REFERENCES LOAI_PHONG(MaLoai),
    FOREIGN KEY (MaTrangThai) REFERENCES TRANGTHAI_PHONG(MaTrangThai)
);
CREATE TABLE THIETBI (
    MaTB CHAR(10) PRIMARY KEY,
    TenTB NVARCHAR(100),
    DonViTinh NVARCHAR(20),
    TinhTrang NVARCHAR(50)
);
CREATE TABLE PHONG_THIETBI (
    MaPhong CHAR(10),
    MaTB CHAR(10),
    SoLuong INT CHECK (SoLuong >= 0),
    PRIMARY KEY (MaPhong, MaTB),
    FOREIGN KEY (MaPhong) REFERENCES PHONG(MaPhong),
    FOREIGN KEY (MaTB) REFERENCES THIETBI(MaTB)
);
CREATE TABLE DONVI (
    MaDonVi CHAR(10) PRIMARY KEY,
    TenDonVi NVARCHAR(100),
    DiaChi NVARCHAR(200),
    SDT VARCHAR(15)
);
CREATE TABLE NHANVIEN (
    MaNV CHAR(10) PRIMARY KEY,
    HoTen NVARCHAR(100),
    ChucVu NVARCHAR(50),
    Email NVARCHAR(100),
    SDT VARCHAR(15),
    MaDonVi CHAR(10),
    FOREIGN KEY (MaDonVi) REFERENCES DONVI(MaDonVi)
);
CREATE TABLE NGUOIDUNG (
    TenDangNhap VARCHAR(50) PRIMARY KEY,
    MatKhau VARCHAR(50),
    Quyen NVARCHAR(50),
    MaNV CHAR(10),
    FOREIGN KEY (MaNV) REFERENCES NHANVIEN(MaNV)
);
CREATE TABLE PHIEUDANGKY (
    MaPDK CHAR(10) PRIMARY KEY,
    NgayDangKy DATE,
    MaNV CHAR(10),
    GhiChu NVARCHAR(200),
    FOREIGN KEY (MaNV) REFERENCES NHANVIEN(MaNV),
);
CREATE  TABLE CHITIET_PHIEUDANGKY (
    MaPDK CHAR(10),
    MaPhong CHAR(10),
    NgaySuDung DATE,
    GioBatDau TIME,
    GioKetThuc TIME,
	NguoiSuDung NVARCHAR(50),
    MucDich NVARCHAR(200),
    PRIMARY KEY (MaPDK, MaPhong, NgaySuDung),
    FOREIGN KEY (MaPDK) REFERENCES PHIEUDANGKY(MaPDK),
    FOREIGN KEY (MaPhong) REFERENCES PHONG(MaPhong)
);

CREATE TABLE TRANGTHAI_BAOTRI (
    MaTrangThaiBT CHAR(10) PRIMARY KEY,
    TenTrangThai NVARCHAR(50)
);

CREATE TABLE LICH_BAO_TRI (
    MaBaoTri CHAR(10) PRIMARY KEY,
    MaPhong CHAR(10),
    MaTB CHAR(10) NULL,
    NgayBatDau DATE,
    NgayKetThuc DATE,
    NoiDung NVARCHAR(200),
    MaTrangThaiBT CHAR(10),
    FOREIGN KEY (MaPhong) REFERENCES PHONG(MaPhong),
    FOREIGN KEY (MaTB) REFERENCES THIETBI(MaTB),
    FOREIGN KEY (MaTrangThaiBT) REFERENCES TRANGTHAI_BAOTRI(MaTrangThaiBT)
);